name: health
version: "0.0.0.1"

default-extensions:
  - BlockArguments
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - NumericUnderscores
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies  

dependencies:
  - async
  - base
  - bytestring
  - containers
  - network
  - optics
  - optics-extra
  - primitive
  - process
  - safe-exceptions
  - signal
  - stm
  - unix

executables:
  health:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
